wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650048446
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      4: 3.9.7
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
dropout:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0001
skip_mlps:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.01
